# .github/workflows/auto-merge-on-test.yml
name: Auto-Merge on Conda-Forge Test Pass

on:
  check_suite:
    types: [completed]  # Trigger when a check suite completes

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure the check suite has passed
        uses: actions/github-script@v6
        id: check-suite
        with:
          script: |
            const { data: checkSuite } = await github.rest.checks.listSuitesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref
            });
            
            const checkSuiteId = checkSuite.check_suites.find(cs => cs.app.slug === 'conda-forge' && cs.status === 'completed').id;
            const { data: checkRuns } = await github.rest.checks.listForSuite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_suite_id: checkSuiteId
            });
            
            const allChecksPassed = checkRuns.check_runs.every(run => run.conclusion === 'success');
            
            if (allChecksPassed) {
              return true;
            } else {
              return false;
            }

      - name: Auto Merge Pull Request
        if: steps.check-suite.outputs.result == 'true'
        uses: pascalgn/automerge-action@v0.15.0
        with:
          merge_method: squash  # or 'merge', 'rebase' based on your preference
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
